CREATE TABLE IF NOT EXISTS users (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    github_id BIGINT UNSIGNED NOT NULL,
    username VARCHAR(255) NOT NULL,
    avatar_url VARCHAR(512) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uniq_github_id (github_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
